import React from 'react';
import PageLayout from '@/components/PageLayout';
import PageHero from '@/components/PageHero';
import SectionHeading from '@/components/SectionHeading';
import CTASection from '@/components/CTASection';
import { IMAGES } from '@/lib/images';
import {
  Leaf, Fuel, Wind, Shield, TrendingDown, Building2, Globe, Sun,
  CheckCircle2, ArrowRight, Droplets, TreePine, BarChart3
} from 'lucide-react';
import { Link } from 'react-router-dom';

const Sustainability: React.FC = () => {
  return (
    <PageLayout>
      <PageHero
        image={IMAGES.futuristicIsland}
        label="Sustainability"
        title="Cleaner energy for island communities"
        description="Solar energy is not just about cost savings. It is about building resilient, lower-carbon, and more self-sufficient island infrastructure."
      />

      {/* Why Sustainability Matters */}
      <section className="py-20 lg:py-24">
        <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
          <div className="grid grid-cols-1 lg:grid-cols-2 gap-16 items-center">
            <div>
              <SectionHeading
                label="The Case for Change"
                title="Why sustainability matters in the Maldives"
                align="left"
              />
              <div className="space-y-4 text-gray-700 leading-relaxed">
                <p>
                  The Maldives faces a unique energy challenge. Nearly every inhabited island depends on imported diesel fuel for electricity generation. This creates high operating costs, supply chain vulnerability, and a significant carbon footprint — all in a country that is among the most vulnerable to climate change.
                </p>
                <p>
                  Solar energy offers a practical, proven path to lower emissions, reduced diesel dependence, and greater energy resilience. For homes, it means lower electricity bills. For resorts, it means stronger sustainability credentials. For businesses, it means lower operating costs. For islands, it means a more secure energy future.
                </p>
                <p>
                  At M South Solar, sustainability is not a marketing slogan. It is the practical outcome of every system we design and install.
                </p>
              </div>
            </div>
            <div>
              <img src={IMAGES.resort} alt="Sustainable resort" className="rounded-2xl shadow-2xl w-full" />
            </div>
          </div>
        </div>
      </section>

      {/* Benefits Grid */}
      <section className="py-20 lg:py-24 bg-gray-50">
        <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
          <SectionHeading
            label="Impact Areas"
            title="How solar drives sustainability"
            description="Every solar installation contributes to multiple sustainability outcomes — from immediate cost savings to long-term environmental benefits."
          />
          <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 gap-8">
            {[
              { icon: Fuel, title: 'Lower Diesel Dependence', desc: 'Every kilowatt-hour generated by solar is a kilowatt-hour not generated by diesel. This reduces fuel imports, lowers costs, and improves energy security for island communities.' },
              { icon: Wind, title: 'Reduced Carbon Emissions', desc: 'Solar energy produces zero direct emissions during operation. Replacing diesel generation with solar directly reduces the carbon footprint of homes, businesses, and public facilities.' },
              { icon: Shield, title: 'Energy Security & Resilience', desc: 'Solar-plus-battery systems provide backup power during grid outages and reduce dependence on fuel supply chains that can be disrupted by weather or logistics challenges.' },
              { icon: BarChart3, title: 'Stronger ESG Credentials', desc: 'For resorts and businesses, solar installations demonstrate tangible environmental commitment — supporting ESG reporting, sustainability certifications, and guest expectations.' },
              { icon: TrendingDown, title: 'Lower Operating Costs', desc: 'Solar energy reduces long-term electricity costs. For properties with high air-conditioning loads, the savings can be substantial over the system lifetime.' },
              { icon: Globe, title: 'Cleaner Growth', desc: 'As the Maldives builds new infrastructure — homes, guest houses, commercial facilities — integrating solar from the start creates cleaner, more efficient buildings.' },
            ].map((item, i) => (
              <div key={i} className="bg-white rounded-2xl p-8 border border-gray-100 hover:shadow-lg transition-all group">
                <div className="w-12 h-12 bg-[#06D6A0]/10 rounded-xl flex items-center justify-center mb-5 group-hover:bg-[#06D6A0] transition-colors">
                  <item.icon className="w-6 h-6 text-[#06D6A0] group-hover:text-white transition-colors" />
                </div>
                <h3 className="text-lg font-bold text-[#0A2540]">{item.title}</h3>
                <p className="text-sm text-gray-600 leading-relaxed mt-2">{item.desc}</p>
              </div>
            ))}
          </div>
        </div>
      </section>

      {/* Sustainability by Sector */}
      <section className="py-20 lg:py-24">
        <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
          <SectionHeading
            label="By Sector"
            title="Sustainability across property types"
          />
          <div className="space-y-8">
            {[
              { title: 'For Homes & Villas', desc: 'Household solar reduces monthly electricity bills, provides backup power during outages, and contributes to the national renewable energy target. With net metering, excess energy feeds back to the grid — turning your roof into a productive asset.', img: IMAGES.villa },
              { title: 'For Guest Houses & Resorts', desc: 'Hospitality properties face growing pressure from guests, tour operators, and certification bodies to demonstrate environmental responsibility. Solar installations provide measurable sustainability impact — from reduced diesel consumption to lower carbon emissions per guest night.', img: IMAGES.guestHouse },
              { title: 'For Commercial & Industrial Facilities', desc: 'Large commercial roofs offer significant solar potential. For warehouses, offices, and industrial facilities, solar reduces operating costs while supporting corporate sustainability goals and regulatory compliance.', img: IMAGES.commercial },
            ].map((item, i) => (
              <div key={i} className={`grid grid-cols-1 lg:grid-cols-2 gap-12 items-center ${i % 2 === 1 ? 'lg:flex-row-reverse' : ''}`}>
                <div className={i % 2 === 1 ? 'lg:order-2' : ''}>
                  <img src={item.img} alt={item.title} className="rounded-2xl shadow-lg w-full" />
                </div>
                <div className={i % 2 === 1 ? 'lg:order-1' : ''}>
                  <h3 className="text-2xl font-bold text-[#0A2540]">{item.title}</h3>
                  <p className="text-gray-700 leading-relaxed mt-4">{item.desc}</p>
                  <Link to="/contact" className="inline-flex items-center gap-2 text-[#00A896] font-semibold mt-4 hover:gap-3 transition-all">
                    Discuss your project <ArrowRight className="w-5 h-5" />
                  </Link>
                </div>
              </div>
            ))}
          </div>
        </div>
      </section>

      {/* Carbon-Conscious Island */}
      <section className="relative py-20 lg:py-24 overflow-hidden">
        <div className="absolute inset-0">
          <img src={IMAGES.futuristicIsland} alt="" className="w-full h-full object-cover" />
          <div className="absolute inset-0 bg-[#0A2540]/85" />
        </div>
        <div className="relative max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
          <div className="max-w-3xl mx-auto text-center">
            <span className="inline-block text-xs font-semibold uppercase tracking-[0.15em] text-[#06D6A0] mb-3">The Vision</span>
            <h2 className="text-3xl sm:text-4xl lg:text-5xl font-bold text-white leading-tight">
              Toward the carbon-conscious island
            </h2>
            <p className="mt-6 text-lg text-white/70 leading-relaxed">
              Imagine a Maldives where every island generates a significant share of its electricity from solar. Where homes, guest houses, resorts, and public buildings all contribute to a cleaner, more resilient energy system. Where diesel generators run less, emissions fall, and island communities benefit from lower costs and greater energy independence.
            </p>
            <p className="mt-4 text-lg text-white/70 leading-relaxed">
              This is not a distant dream. The technology exists. The policy support is growing. The economics are increasingly favourable. Every solar installation — from a 3 kW home system to a megawatt-scale resort project — moves the Maldives closer to this vision.
            </p>
            <p className="mt-4 text-lg text-white/70 leading-relaxed">
              M South Solar is committed to being part of this transition — one rooftop, one island, one project at a time.
            </p>
            <div className="mt-10 flex flex-col sm:flex-row items-center justify-center gap-4">
              <Link
                to="/contact"
                className="inline-flex items-center gap-2 px-8 py-4 bg-[#06D6A0] hover:bg-[#05C090] text-[#0A2540] font-semibold rounded-xl transition-all"
              >
                Start your solar journey <ArrowRight className="w-5 h-5" />
              </Link>
              <Link
                to="/solar-maldives"
                className="inline-flex items-center gap-2 px-8 py-4 bg-white/10 hover:bg-white/20 text-white font-semibold rounded-xl border border-white/20 transition-all"
              >
                Explore the Maldives solar market
              </Link>
            </div>
          </div>
        </div>
      </section>

      <CTASection
        title="Ready to make your property part of the solution?"
        description="Contact us for a site survey, solar proposal, or sustainability assessment. We will help you understand the impact solar can have on your energy costs and environmental footprint."
      />
    </PageLayout>
  );
};

export default Sustainability;
